version: '3'
services:
    vue:
      image: amaymon8/mdc-vue-csv:latest
      ports:
        - 8080:8080    
      container_name: vue-csv
      networks:
        - myappnetwork
      
    python:
      image: amaymon8/mdc-python-csv:latest
      container_name: python-csv
      ports:
        - 8000:8000
      networks:
        - myappnetwork
      environment:
        - AUTH_TOKEN=enter your token here
      depends_on:
        - db    
    db:
      image: postgres:latest
      restart: always
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=bridge-db
      ports:
        - "5858:5432"
      networks:
        - myappnetwork
      volumes:
        - ./data:/var/lib/postgresql/data
networks:
  myappnetwork: