version: '3'
services:
    watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --interval 300
      networks:
        - myappnetwork
    python:
      image: amaymon8/mdc-python-csv:latest
      container_name: python-csv
      ports:
        - 8000:8000
      networks:
        - myappnetwork
      environment:
        - AUTH_TOKEN=enter your token here
      depends_on:
        - db
      labels:
        - com.centurylinklabs.watchtower.enable=tru
    db:
      image: postgres:latest
      restart: always
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=bridge-db
      ports:
        - "5858:5432"
      networks:
        - myappnetwork
      volumes:
        - ./data:/var/lib/postgresql/data
networks:
  myappnetwork:
    external: true